# Generated by Django 3.1.2 on 2023-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='item',
            name='hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('5', '全新'), ('4', '幾乎全新'), ('3', '狀況良好'), ('2', '輕度使用'), ('1', '狀況尚可'), ('0', '免費送出')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
